### ISSUE TITLE
UwUified python logo

### ISSUE THREAD

**Issue by SystematicError** [SystematicError/Pwython#5]
Create a variation of the python logo but uwuified

**Comment by NISH-Original** [comment]
How's this?
![image](https://user-images.githubusercontent.com/75113251/134502365-52d43235-8a99-4668-b8e2-c700f598a687.png)

**Comment by SystematicError** [comment]
Looks nice! Perhaps some tweaks to the placement, I'll try doing one myself later.

**Comment by NISH-Original** [comment]
sure mate no probs 😀👍

**Comment by SystematicError** [comment]
I just remembered about this, probably gonna finish it by this week :)

**Comment by SystematicError** [comment]
Commits 120aaa0cde513e64be3e074736598fa67b8022b7 and 1210b9f886ad18efcf81202d56c7102749755710 updates the branding, I'll update the github social card right now, thanks for being patient :)
