### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by sheeepdev** [SystematicError/Pwython#6]
pwease i want to remove i am infected by uwu pwease help me uninstall this so i can return to my life

**Comment by SystematicError** [comment]
There is no uninstallation, once pwython, forever pwython >:)

**Comment by SystematicError** [comment]
On a serious note, you can uninstall it via pip, using `pip uninstall pwython`

![image](https://user-images.githubusercontent.com/63366086/143046025-b3cc190f-9702-41e9-a0d9-2593701e7774.png)

**Comment by sheeepdev** [comment]
Twank you wevy much!!!
